name: Main Build
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: npm
      - run: npm ci
  format:
      runs-on: ubuntu-latest
      needs: [setup]
      name: Check formatting
      steps:
        - uses: actions/checkout@v3
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
            cache: npm
        - run: npm ci
        - run: npm run format:check
  lint:
      runs-on: ubuntu-latest
      needs: [setup]
      name: Lint
      steps:
        - uses: actions/checkout@v3
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
            cache: npm
        - run: npm ci
        - run: npm run lint
  build:
      runs-on: ubuntu-latest
      needs: [setup]
      name: Build
      steps:
        - uses: actions/checkout@v3
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
            cache: npm
        - run: npm ci
        - run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: [setup]
    name: Test
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: npm
      - run: npm ci
      - run: npm test
  release:
    name: Release
    needs: [build, lint, format, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: npm
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install Dependencies
        run: npm ci
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}